# Generated by Django 4.1 on 2022-08-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_view_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
