# Generated by Django 4.1 on 2022-08-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
