# Generated by Django 4.1 on 2022-08-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='update_date',
            new_name='updated',
        ),
    ]
