# Generated by Django 4.1 on 2022-08-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_commentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
