# Generated by Django 4.1 on 2022-08-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_owninterests_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='about_me',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('idk', 'idk')], default='idk', max_length=6),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
